### ISSUE TITLE
Disable JAR scanning to boost startup times

### ISSUE THREAD

**Issue by utdream** [utdream/CFML-Installers#65]
According to Igal on the Lucee mailing list. Suggested config:

in Tomcat/conf/catalina.properties set:

    tomcat.util.scan.StandardJarScanFilter.jarsToSkip=*.jar

**Comment by TwentyOneSolutions** [comment]
IIRC this is Tomcat 8's property.  in Tomcat 7 the property's path is slightly different, but still ends with `jarsToSkip`

**Comment by TwentyOneSolutions** [comment]
please see https://github.com/utdream/CFML-Installers/pull/66

**Comment by utdream** [comment]
Implementing this into Lucee Installer 4.5.1.022 with Tomcat 8 as well.

**Comment by utdream** [comment]
https://github.com/utdream/CFML-Installers/wiki/Lucee-Installer-Release-Notes

**Comment by coffeeburrito** [comment]
@utdream this fix was broken in lucee-4.5.1.022-pl0, which replaced `*.jar` with `+*.jar`

https://github.com/viviotech/lucee-installer/blob/3340fd18bd154145171f4af640abb74c9f2b12fe/lucee/tomcat8/tomcat/conf/catalina.properties#L133
