### ISSUE TITLE
mod_cfml install script needs to fail gracefully if no apache installed.

### ISSUE THREAD

**Issue by utdream** [utdream/CFML-Installers#67]
As reported by Brad Wood:
https://groups.google.com/forum/#!topic/lucee/5KTAG3CPlLM

**Comment by utdream** [comment]
Turns out we just need to update the mod_cfml install script. (need to update it for mod_cfml 1.1 anyway) and have it fail gracefully if no apache is intalled. Looks like mod_proxy install script already fails gracefully.

**Comment by bdw429s** [comment]
Thanks!

**Comment by utdream** [comment]
mod_cfml install is now optional
